Implements banning and marshal/unmarshal chat.Message
JungleMC/standalone pull request #15
Opened 2021-06-13 01:56 UTC by the-furry-hubofeverything

I don't know if you approve of this way of kicking people :P

Also, I don't know how this would work with the current way of config in .toml or environment variables. On vanilla it just appends to a file and update on the fly. With either of the options, you would have to restart the server. I just put it in as a toml option for now.

2021-06-13 02:05 UTC, the-furry-hubofeverything commented
I also added field names to the debug messages for packet structs and I have a question in `internal/pkg/net/packets/play_clientbound.go`, I wasn't sure about the breaks in the switch statement.

2021-07-02 11:39 UTC, Ella-Fox requested changes
I'm going to keep this PR as pending until a data storage method is decided upon. The codebase isn't quite ready for player bans yet, but thanks for the contribution :3

2021-07-02 11:39 UTC, Ella-Fox commented on README.md
> -Minecraft server software, written from the ground-up in Go.
Can changes to this file please be ignored

2021-07-02 11:39 UTC, Ella-Fox commented on internal/configuration/configuration.go
> +	BannedPlayers    []Ban
This configuration file is supposed to be static, and should not include data that can be changed on-the-fly (eg, banning a player who is currently online). It would probably be better to go into LevelDB or some other persistent storage, since the goal is eventually going to instance clustering

2021-07-02 11:39 UTC, Ella-Fox commented on internal/net/online_player.go
> +	for _, bannedPlayer := range configuration.Config().BannedPlayers {
Implementation is fine, but the location of the banned players needs to change as per my previous comment. Honestly it might be a good idea to come back to player bans at a later date

2021-07-02 11:39 UTC, Ella-Fox commented on internal/pkg/net/packets/login_clientbound.go
> -
Ignore this change please

2021-07-02 11:39 UTC, Ella-Fox commented on internal/pkg/net/packets/play_clientbound.go
> +	// Unclear, break out of the for loop or break out of the switch?
Break applies to switch statements here. We could use a label to make it clearer

2021-07-02 11:39 UTC, Ella-Fox commented on pkg/chat/message.go
> +func (c *Message) MarshalMinecraft() ([]byte, error) {
Nice, thank you ^^

2021-07-02 11:40 UTC, Ella-Fox commented
Also worth mentioning, chat.Message ought to be implemented in a separate PR so that it doesn't get left out

2021-08-09 05:18 UTC, the-furry-hubofeverything commented
I'm closing this PR and opening another one so it's tidier.

2021-08-09 05:18 UTC, closed without merging